### ISSUE TITLE
Multiple Server Support / Timestamp Release Support

### ISSUE THREAD

**Issue by mojojoseph** [mina-deploy/mina#217]
Howdy - I'm new to Mina and am coming from a Capistrano background.  

I'm curious as to the current level of support for deploying to multiple servers at a time.  We have a farm of servers that are running the same Rails codebase and I'd like to be able to update all of the servers simultaneously or in a roundrobin fashion.  More over, the deployed code really should have a unified timestamp across each of the servers - rather than releases/1 releases/2, etc. something like 20140812000000 etc.  Or does the community tend to deploy to a shared directory such as an NFS mount for these things?

**Comment by d4be4st** [comment]
As mina works now this would not be possible.
Mina creates a bash script and then executes it via ssh command.
You would need to make a task that would run multiple mina deploys with different deploy.rb config files.

As for the timestamps, many of us prefer the sequential numbering instead of the timestamp. 
There is a pull request #49 which enables this but the author never rebased his PR.

**Comment by sergeifilippov** [comment]
This could help a little with  the multi server deploy. https://github.com/endoze/mina-multistage
