### ISSUE TITLE
Mina - Foreman - Bundle problem

### ISSUE THREAD

**Issue by seyhunak** [mina-deploy/mina#257]
I'm using ruby 2.1.5 mri, and mina (0.3.1). rbenv 0.4.0-129-g7e0e85b, and rbenvsudo plugin.
But cannot deployed properly,  foreman cannot initalize bundler. What is the problem in here?

Here is the mina verbose output;

### Mina trace output
    -----> Exporting foreman procfile for app
    $ cd /home/deployer/app/current ; sudo bundle exec foreman export upstart /etc/init -a app -u     deployer -d /home/deployer/app/current -l /home/deployer/app/shared/log
    bash: line 168: cd: /home/deployer/app/current: No such file or directory
    sudo: bundle: command not found
    ! ERROR: Deploy failed.
    -----> Cleaning up build
    $ rm -rf "$build_path"
    Unlinking current
    $ rm -f "deploy.lock"
    OK

### /etc/sudoers
root     ALL=(ALL:ALL) ALL
deployer ALL=(ALL:ALL) NOPASSWD:ALL

### ~/.bashrc
export PATH="$home/.rbenv/bin:$PATH"
export PATH=~/.rbenv/shims:~/.rbenv/bin:"$PATH"
eval "$(rbenv init -)"
export RAILS_ENV=production

### /root/.bashrc
Same as ~/.bashrc

**Comment by kofronpi** [comment]
I feel like there are still  bugs with the foreman module. I encountered a lot of problems from closed issues while trying to do the first deploy (e.g. current symlink broken and folder not yet existing -> `foreman:export` breaks, because there has never been a deploy yet...)

Also, @gabskoro what you say is differerent from the documentation where `foreman:export` is not called in the launch block ?
