### ISSUE TITLE
RVM is not a function

### ISSUE THREAD

**Issue by harryworld** [mina-deploy/mina#262]
I have setup the mina to a new server on `1and1.fr` Ubuntu 14.04 dedicated server, with `rvm 1.26.4` and `ruby 2.1.5`, if I logged in as `ubuntu` user, I can run rvm successfully, but if I use `mina setup`, it tells me the following error message on not using interactive shell. 

Is there anyway to `mina` using login shell by default? Or switch to login shell after logging in?

```
require 'mina/rvm'
set :user, 'ubuntu'

task :environment do
  invoke :'rvm:use[ruby-2.1.5]'
end
```

```
You need to change your terminal emulator preferences to allow login shell.
       Sometimes it is required to use `/bin/bash --login` as the command.
       Please visit https://rvm.io/integration/gnome-terminal/ for an example.
```

**Comment by mrozbarry** [comment]
+1 I've been fidgetting for the last 2 hours trying to get it to work.

**Comment by mhuggins** [comment]
+1

**Comment by mhuggins** [comment]
```
RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.

Please visit https://rvm.io/integration/gnome-terminal/ for an example.
```

**Comment by mhuggins** [comment]
@harryworld @mrozbarry did either of you get this working, or did you abandon mina?

**Comment by mhuggins** [comment]
I figured it out!  I had to change this line in my `deploy.rb` file from:

```ruby
set :rvm_path, '/usr/local/rvm/bin/rvm'
```

to this:

```ruby
set :rvm_path, '/usr/local/rvm/scripts/rvm'
```

The reason is that for a non-login, rvm must be sourced to run as a function instead of trying to run it as a binary [as explained here](https://rvm.io/workflow/scripting).  I was originally trying to add this to my server's user's `.bashrc` with no luck, not realizing that the deploy screen was also calling `source` with the value of `rvm_path`, which ultimately overwrote that setting.

Note that you might need to set rvm path to `~/.rvm/scripts/rvm` if not using a system-wide installation.

**Comment by d4be4st** [comment]
Thank @mhuggins for figuring this out!

**Comment by harryworld** [comment]
@mhuggins  I keep on using `mina`, it works without configuring that properly.
I tried your way, and it works now. Thanks.

**Comment by adiakritos** [comment]
I saw that already and it still doesn't work for me. I can use rvm when I log in manually but mina can't do it.

**Comment by adiakritos** [comment]
Figured out the issue. 

When logged in manually I'm able to run rvm from this path:

'/usr/local/rvm/scripts/rvm'

So I thought that this is what mina should use. I kept reading paths in the answers provided that look like this: ~/.rvm/scritpts/rvm  leading me to think they are not my path..

I turns out that I too have a folder called /scripts and an exe rvm in there. So my path is this:

/usr/local/rvm/scripts/rvm 

This seemed to fix that issue. I have a different one now though :(

**Comment by flowerett** [comment]
That's because you're installed the `rvm` *globally* or for *multi-user*
But *Single-User Install* seems more general, so I don't think that we have an issue here.
more info: https://rvm.io/rvm/install#installation
And it's up to you to choose a path that you more comfortable with, just set your `rvm_path` like this:
```ruby
set :rvm_path, '/usr/local/rvm/scripts/rvm'
```
as mentioned above.

**Comment by nezirz** [comment]
In my case fix was change to `set :rvm_use_path, '/home/deploy/.rvm/scripts/rvm'` from `set :rvm_use_path, '/home/deploy/.rvm/bin/rvm'`
