### ISSUE TITLE
The old "force_assets=1" option is mentioned on the "rails:assets_precompile" doc webpage rather than the new "force_asset_precompile=true" one

### ISSUE THREAD

**Issue by mrj** [mina-deploy/mina#520]
The [rails:assets_precompile](http://nadarei.co/mina/tasks/rails_assets_precompile.html) doc webpage should be updated to mention the new ```force_asset_precompile=true``` option rather than the old ```force_assets=1``` one, which no longer works.

**Comment by lowjiayou** [comment]
I keep getting `-----> Skipping asset precompilation` though it is a new deployment.
I have checked that my project's "current/public/assets" is pointing to "shared/public/assets", and it is empty inside.
By adding `force_asset_precompile=true` parameter do solve my problem. 
But shouldn't that precompilation run without problem? 

Note: 
I've change the standard flow of "mina deploy" for my project that's why asset precompile had run to separately. I wish to use `invoke :'rails:assets_precompile'` without extra parameter so that deployment script is much simpler.

**Comment by d4be4st** [comment]
because to be fast, mina checks diffs of your assets between deploys. if you deploy the same code twice, the second time there wont be any difference between your assets and it will skip precompiling

**Comment by d4be4st** [comment]
Unfortunately i do not have access to http://nadarei.co/mina/tasks/rails_assets_precompile.html to change that documentation :(
