### ISSUE TITLE
SSH Connection

### ISSUE THREAD

**Issue by Thadeu** [mina-deploy/mina#608]
How to use other id_rsa.pub in connection ssh?

eg.

I have some id_rsa_some.pub, I'd like use this file in my deploy.

How to do this?

**Comment by mark100net** [comment]
Since you referenced the .pub file I'm not sure what you are trying to do. That goes on the server (in authorized_keys).

I also wanted to use other than the default key file name so I looked at the code and found that there is already an option for this (after manually copying over the public key file to authorized keys):

In config/deploy.rb:

    set :identity_file, '~/.ssh/id_rsa_some' # local full path to private key file

**Comment by Thadeu** [comment]
@mark100net That's right! Was that it same, thanks a lot for your help.
