### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by borama** [mina-deploy/mina#642]
Hello,

we are considering switching from Capistrano to Mina but this project seems stale (again - #181, #541) now. Is it maintained? Do you perhaps need more collaborators?

Thanks!

**Comment by mcescalante** [comment]
This is not an answer to your original question and is pretty verbose, but I started using mina many years ago while it was still in it's 0.x.x version and still have a few small projects using it. There has been little to no changes or movement for a while now in both the library or ecosystem. I'm aware that software can be stable and well with infrequent updates, so I don't just want this to come across as "you must commit often or your project is dead to me".

I have switched my projects to Ansible with the `deploy_helper` module which replicates the releases w/ history, rollbacks, shared paths, and the other things I like most about mina/cap. There are also "ansible ports" such as https://github.com/ansistrano/deploy and you can likely find other examples out there on the web. I have switched primarily for the additional features, community & resources, and because I'm using Ansible for other parts of my infra.

I don't have any detailed performance/timing data for Mina (2.0.0 or 0.3.8) versus an Ansible deployments. I am aware that as noted in the readme, Mina is a bash script generator and that (Capistrano and) Ansible probably actually open more SSH connections to complete a task, but I prefer to have a pluggable system with an active ecosystem _(and you can enable `pipelining=True` which reduces the SSH overhead for Ansible to a couple seconds of waiting)_.

**Comment by asabourin** [comment]
Just chiming in here we've also been using mina for most of our apps for years and are very happy with it even though it doesn't get updated very often.
It's quick and easy to understand and extend for any of our needs so we even ended up writing a plugin to manage deployment to Kubernetes: https://github.com/streemau/mina-kubernetes.
Hopefully the maintainer will have time to work on the project again.

**Comment by NBuhinicek** [comment]
Hey there

Yes, the project is still alive. Lot of stuff going on but we're here to finally help with some issues and fixes :)
