### ISSUE TITLE
Command runs during deploy, but not when called independently

### ISSUE THREAD

**Issue by wedtm** [mina-deploy/mina#82]
I have the following in my deploy.rb: https://gist.github.com/4475871

When I run `mina deploy`, Sidekiq is started just as it should be.

However, if I kill sidekiq, and then run `mina sidekiq:start`, it never runs. I get this message:

```
> mina sidekiq:start --verbose                                                                                                                                              1.9.3p194 master@2ac0d22+rebase ✗
-----> Start sidekiq
$ (cd /var/www/site/current && nohup bundle exec sidekiq -e production -C ./config/sidekiq.yml -P /var/www/site/shared/tmp/pids/sidekiq.pid >> ./log/sidekiq.log 2>&1 </dev/null &) 
Connection to devbox.lcl closed.
       Elapsed time: 1.00 seconds
```

**Comment by jamesmarkcook** [comment]
@wedtm @mikong I realise this is a very old problem that is apparently fixed, but I am also encountering this issue 2 years later on v0.3.2.

For some reason, the issue seems to be caused by Mina closing the connection to the server before Sidekiq can be fully daemonized. The fix I used is to add `queue 'sleep 1'` after the Sidekiq command in the start task.
